export const data = [
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Smooth Log",
    description: "ingredients_description",
    name: "smooth_log",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Hard Log",
    description: "ingredients_description",
    name: "hard_log",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Coarse Log",
    description: "ingredients_description",
    name: "coarse_log",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Emerald",
    description: "ingredients_description",
    name: "raw_emerald",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Diamond",
    description: "ingredients_description",
    name: "raw_diamond",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Demonite",
    description: "ingredients_description",
    name: "raw_demonite",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Ruby",
    description: "ingredients_description",
    name: "raw_ruby",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Fine Cloth Scrap",
    description: "ingredients_description",
    name: "fine_cloth_scrap",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Soft Cloth Scrap",
    description: "ingredients_description",
    name: "soft_cloth_scrap",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Soft Pelt",
    description: "ingredients_description",
    name: "fine_pelt",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Soft Pelt",
    description: "ingredients_description",
    name: "soft_pelt",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Morganite",
    description: "ingredients_description",
    name: "raw_morganite",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Gold",
    description: "ingredients_description",
    name: "raw_gold",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Iron",
    name: "raw_iron",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Ancient Roots",
    name: "ancient_roots",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Rotten Log",
    name: "rotten_log",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Sturdy Stick",
    name: "sturdy_stick",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Shiny Stone",
    name: "shiny_stone",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Bone",
    name: "raw_bone",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Monster Blood",
    name: "monster_blood",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Tattered Pelt",
    name: "tattered_pelt",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Spools of Thread",
    name: "spools_of_thread",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Rough Cloth Scrap",
    name: "rough_cloth_scrap",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Rough Pelt",
    name: "rough_pelt",
    description: "Ingredient Description",
    ingredients: [],
  },

  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Tattered Cloth Scrap",
    name: "tattered_cloth_scrap",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Plant Fiber",
    name: "plant_fiber",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Raw Carnelian",
    name: "raw_carnelian",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Worn Cloth of Scrap",
    name: "worn_cloth_of_scrap",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Worn Pelt",
    name: "worn_pelt",
    description: "Ingredient Description",
    ingredients: [],
  },
  {
    craftable_amount: null,
    type: "ingredients",
    viewValue: "Moldy Log",
    name: "moldy_log",
    description: "Ingredient Description",
    ingredients: [],
  },
];
export const ingredients = () => {
  const nameList = data.map((v) => v.name);
  nameList.forEach((str) => {
    const dublicates = nameList.filter((name) => name === str);
    if (dublicates.length > 1) {
      throw new Error(`Dublicates found: ${str}`);
    }
  });
  // console.log("Ingredients does not have dublicates.");
  return data;
};
